version: "3.1"

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql_ing
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
